SELECT
    CUSTOMERS.ID AS CUSTOMER_ID,
    CUSTOMERS.FIRST_NAME,
    CUSTOMERS.LAST_NAME,
    COALESCE(COUNT(ORDERS.ID), 0) AS NUMBER_OF_ORDERS,
    MAX(ORDERS.ORDER_DATE) AS MOST_RECENT_ORDER_DATE,
    MIN(ORDERS.ORDER_DATE) AS FIRST_ORDER_DATE
FROM
    {{ source('dbt_raw', 'customers') }} CUSTOMERS
    LEFT OUTER JOIN {{ source('dbt_raw', 'orders') }} ORDERS ON (ORDERS.USER_ID = CUSTOMERS.ID)
GROUP BY
    1, 2, 3
